### ISSUE TITLE
Check for Non-Classed CSS

### ISSUE THREAD

**Issue by BradKriss** [BrandXads/leaf-landers#53]
I was trying to upload terms and there's an unordered list in the T&Cs. Using a plain `<ul>` & `<li>` tags the text was white, then I found this CSS code.

```css
ul{
    list-style: none;
    margin-top: 40px;
    padding-left: 20px;
    margin-bottom: 20px;
}

li{
    display: list-item;
    color: #FFF;
    margin-bottom: 5px;
    width: 100%;
}
```

This is a good example of why you should never just define a style for a base html tag.

You can use base tags when nesting in CSS like:

```scss
.modal-form {
   li {
      color: white
   }
}
```

But even that you want to make sure you have enough receptivity so it doesn't break something else. The following code would be better even as the code would only apply to modals with a green BG.

```scss
.modal-form.green-bg {
   li {
      color: white
   }
}
```

Anyways, go through the SCSS files and if there are any other cases of styling base html elements add classes to them.

For an example I edited the SCSS to

```scss
#signup-modal {
    .side {
        ul{
            list-style: none;
            margin-top: 40px;
            padding-left: 20px;
            margin-bottom: 20px;
        }
        
        li{
            display: list-item;
            color: #FFF;
            margin-bottom: 5px;
            width: 100%;
        }
    }
}
```
